export const timeZones = [
  { name: 'Eniwetok, Kwajalein', offset: '-12:00' },
  { name: 'Midway Island, Samoa', offset: '-11:00' },
  { name: 'Hawaii', offset: '-10:00' },
  { name: 'Taiohae', offset: '-09:30' },
  { name: 'Alaska', offset: '-09:00' },
  { name: 'Pacific Time (US & Canada)', offset: '-08:00' },
  { name: 'Mountain Time (US & Canada)', offset: '-07:00' },
  { name: 'Central Time (US & Canada), Mexico City', offset: '-06:00' },
  { name: 'Eastern Time (US & Canada), Bogota, Lima', offset: '-05:00' },
  { name: 'Caracas', offset: '-04:30' },
  { name: 'Atlantic Time (Canada), Caracas, La Paz', offset: '-04:00' },
  { name: 'Newfoundland', offset: '-03:30' },
  { name: 'Brazil, Buenos Aires, Georgetown', offset: '-03:00' },
  { name: 'Mid-Atlantic', offset: '-02:00' },
  { name: 'Azores, Cape Verde Islands', offset: '-01:00' },
  { name: 'UTC', offset: '00:00' },
  { name: 'Brussels, Copenhagen, Madrid, Paris', offset: 'UTC+01:00' },
  { name: 'South Africa, Kyiv', offset: 'UTC+02:00' },
  { name: 'Baghdad, Riyadh', offset: 'UTC+03:00' },
  { name: 'Tehran', offset: 'UTC+03:30' },
  { name: 'Abu Dhabi, Muscat, Baku, Tbilisi', offset: 'UTC+04:00' },
  { name: 'Kabul', offset: 'UTC+04:30' },
  { name: 'Islamabad, Karachi, Tashkent', offset: 'UTC+05:00' },
  { name: 'Bombay, Calcutta, Madras, New Delhi', offset: 'UTC+05:30' },
  { name: 'Kathmandu, Pokhara', offset: 'UTC+05:45' },
  { name: 'Almaty, Dhaka, Colombo', offset: 'UTC+06:00' },
  { name: 'Yangon, Mandalay', offset: 'UTC+06:30' },
  { name: 'Bangkok, Hanoi, Jakarta', offset: 'UTC+07:00' },
  { name: 'Beijing, Perth, Singapore, Hong Kong', offset: 'UTC+08:00' },
  { name: 'Eucla', offset: 'UTC+08:45' },
  { name: 'Tokyo, Seoul, Osaka, Sapporo', offset: 'UTC+09:00' },
  { name: 'Adelaide, Darwin', offset: 'UTC+09:30' },
  { name: 'Eastern Australia, Guam', offset: 'UTC+10:00' },
  { name: 'Lord Howe Island', offset: 'UTC+10:30' },
  { name: 'Solomon Islands, New Caledonia', offset: 'UTC+11:00' },
  { name: 'Norfolk Island', offset: 'UTC+11:30' },
  { name: 'Auckland, Wellington', offset: 'UTC+12:45' },
  { name: 'Chatham Islands', offset: 'UTC+13:00' },
  { name: 'Tonga, Samoa', offset: 'UTC+13:45' },
  { name: 'Kiritimati Island', offset: 'UTC+14:00' },
];
