const countries = [
  'Afghanistan',
  'Akrotiri and Dhekelia (United Kingdom)',
  'Aland Islands (Finland)',
  'Albania',
  'Algeria',
  'American Samoa (USA)',
  'American Virgin Islands (USA)',
  'Andorra',
  'Angola',
  'Anguilla (United Kingdom)',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba (Netherlands)',
  'Ashmore and Cartier Islands (Australia)',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Baker Island (USA)',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermudian Islands (United Kingdom)',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island (Norway)',
  'Brazil',
  'British Indian Ocean Territory (United Kingdom)',
  'British Virgin Islands (United Kingdom)',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cape Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cayman Islands (United Kingdom)',
  'Central African Republic',
  'Chad',
  'Chechnya',
  'Chile',
  'China',
  'Christmas Island (Australia)',
  'Clipperton (France)',
  'Cocos Islands (Australia)',
  'Colombia',
  'Comoros Islands',
  'Congo (Democratic Republic)',
  'Coral Sea Islands (Australia)',
  'Cook Islands (New Zealand)',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Curacao (Netherlands)',
  'Cyprus',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Falkland Islands (United Kingdom)',
  'Faroe Islands (Denmark)',
  'Federated States of Micronesia',
  'Fiji',
  'Finland',
  'France',
  'French Polynesia (France)',
  'French Southern and Antarctic Lands (France)',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar (United Kingdom)',
  'Greece',
  'Greenland (Denmark)',
  'Grenada',
  'Guam (USA)',
  'Guatemala',
  'Guernsey (United Kingdom)',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands (Australia)',
  'Honduras',
  'Hong Kong (China)',
  'Howland Island (USA)',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Isle of Man (United Kingdom)',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jersey (United Kingdom)',
  'Jarvis Island (USA)',
  'Johnston Atoll (USA)',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kingman Reef (USA)',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macau (China)',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Midway Atoll (USA)',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat (United Kingdom)',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Navassa Island (USA)',
  'Nepal',
  'Netherlands',
  'New Caledonia (France)',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue (New Zealand)',
  'Norfolk Island (Australia)',
  'North Korea',
  'North Macedonia',
  'Northern Mariana Islands (USA)',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Palmyra Atoll (USA)',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn Islands (United Kingdom)',
  'Poland',
  'Portugal',
  'Puerto Rico (USA)',
  'Qatar',
  'Republic of the Congo',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Barthelemy (France)',
  'Saint Helena, Ascension, and Tristan da Cunha (United Kingdom)',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin (France)',
  'Saint Pierre and Miquelon (France)',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Netherlands)',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands (United Kingdom)',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard (Norway)',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tokelau (New Zealand)',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands (United Kingdom)',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States of America',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican',
  'Venezuela',
  'Vietnam',
  'Wake Island (USA)',
  'Wallis and Futuna (France)',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];

export default countries;
