const programLanguages = [
  'C#/.NET',
  'Android',
  'Angular',
  '2D/3D Artist/Illustrator',
  'Blockchain',
  'Business Analyst',
  'C/C++/Embedded',
  'Data Analyst',
  'Data Engineer',
  'Data Science',
  'Design/UI/UX',
  'DevOp',
  'Drupal',
  'Flutter',
  'Game Designer',
  'Golang',
  'HR',
  'HTML',
  'iOS',
  'Java',
  'JavaScript/Front-End',
  'Laravel',
  'Architect/CTO',
  'Lead Generation',
  'Magento',
  'Marketing',
  'Node.js',
  'PHP',
  'Product Manager',
  'Project Manager',
  'Python',
  'QA Manual',
  'QA Automation',
  'React',
  'React Native',
  'Recruiter',
  'Ruby',
  'Rust',
  'Sales',
  'Salesforce',
  'Scala',
  'Scrum Master/Agile Coach',
  'Security',
  'SEO',
  'SQL/DBA',
  'Customer/Technical Support',
  'Symfony',
  'Sysadmin',
  'Technical Writing',
  'Gamedev/Unity',
  'Unreal',
  'Vue',
  'WordPress',
  'Xamarin'
];

export default programLanguages;
